### PR TITLE
Update Swift 5.0

### PR DESCRIPTION
**Pull request by shiwei93**
Fix errors on Xcode 10.2 and update Swift version to 5.0

### CODE REVIEW

**Comment by JacobSyndeo** [comment]
Hopefully this gets merged in soon…

**Comment by delannoyk** [comment]
@shiwei93 Thanks a lot for doing this!!

**Comment by JacobSyndeo** [comment]
Oh wow!! Thanks @delannoyk, that was crazy fast! 😁

**Comment by delannoyk** [comment]
@JacobSyndeo I reviewed it before and forgot to press the merge button, your comment reminded me 😂 Sorry about that!

**Comment by JacobSyndeo** [comment]
No worries, glad it's in now! I'm looking to move my app from an older player framework called [HysteriaPlayer](https://github.com/StreetVoice/HysteriaPlayer) that I've used since 2012, but is no longer being maintained, and seeing how fast you were to jump on this gives me a great impression of this project. I think you've convinced me that this is the one to go with!

**Comment by delannoyk** [comment]
I haven't been very active on this project lately unfortunately but I'm hoping to get time soon to fix the opened issues and increase the test coverage as well.

**Comment by JacobSyndeo** [comment]
@delannoyk One more thing, could you bump the podspec so that my CocoaPods will see the new Swift 5-compatible version?

**Comment by danielmartinprieto** [comment]
@delannoyk @JacobSyndeo I actively use this project as well for some years now and it's great. Let me know if you need any help reviewing, testing and merging PRs. There are some concrete issues that could be solved, if you have time, @delannoyk, maybe you can review them and prioritize them, I can put some time in development as well, but I'd love if you get involved.

This repo has tons of forks, and I think that if people notice that it's again maintained, they will come back and help creating issues, testing, etc!

**Pull request merged**
