### PR TITLE
Reproduce remote items on queue only if there is WiFi connection

### PR DESCRIPTION
**Pull request by bw0lff**
- added feature to reproduce remote items on queue only if there is WiFi connection.

### CODE REVIEW

**Comment by bw0lff** [comment]
+ added stopPlayerAtEndOfQueue flag, to specify if the queue should be cleared upon last item on queue reproduction ended

**Comment by delannoyk** [comment]
Hi @bw0lff 
Thank you for your contribution. I haven't reviewed all the code yet, but I think this could be a nice addition, although I would suggest another way.
What do you think of adding a delegate method/changing the existing `func audioPlayer(_:willStartPlayingItem:)` to know whether the player *should* start playing the item or skip it?  The default implementation in case the delegate wasn't set would be `true`. This would obviously leave the check for "WiFi" only items to the user of the player, but that would cover any new case that should happen.

**Comment by bw0lff** [comment]
Hi @delannoyk,
The suggestions looks great for me but it should also check if is possible to play any other track on the queue (on my proposal I also changed hasNext and added a hasPrevious to do it). maybe instead of a _:willStartPlayingItem: it should have a _:isItemPlayable:, in order to have it generic delegate for both cases.

**Comment by delannoyk** [comment]
Hi @bw0lff 
I noticed you updated to Swift 2.3! 👍 
Do you want me to close this PR and implement the change we talked about or do you want to update this PR ?
Cheers!

**Comment by bw0lff** [comment]
HI @delannoyk,

Right now I don't have much time to work on this, therefore the best solution might be the 1st one :)

Thanks

**Comment by delannoyk** [comment]
Neither do I, so I'll leave this open until I get some time - maybe in 2 weeks on my side.

**Comment by delannoyk** [comment]
Closing this as #76 will solve this use case.

**Pull request closed without merging**
