### PR TITLE
Refactor & Unit-tests

### PR DESCRIPTION
**Pull request by delannoyk**

### CODE REVIEW

**Comment by delannoyk** [comment]
Not yet available. Still making changes.

**Comment by funkenstrahlen** [comment]
I really appreciate your work on this project. Like to see it getting better all the time 😃

**Comment by delannoyk** [comment]
Thanks 😊

**Comment by delannoyk** [comment]
Going to merge this as a internal refactoring will begin soon (replacing current status handling - should be transparent for users).

**Pull request merged**
